### ISSUE TITLE
Switch to Threatinator for parsing feeds (command-line only)

### ISSUE THREAD

**Issue by justfalter** [cikl/cikl#112]
Switch to [Threatinator](https://github.com/cikl/threatinator) for parsing feeds, and remove legacy perl code.
- [ ] Remove legacy perl Smrt parsing code. 
- [ ] Implement output extension/plugin for Threatinator that puts data into Cikl format and shoves that into RabbitMQ.

Depends upon
- [x] Official gem release of Threatinator cikl/threatinator#42
- [x] Threatinator having pluggable output cikl/threatinator#43
- [x] Ability to provide configuration settings to output plugins cikl/threatinator#48
