### ISSUE TITLE
API and UI Interaction

### ISSUE THREAD

**Issue by dsweet04** [cikl/cikl#77]
This ticket merges tickets #27, #73, and #74 to consolidate and clarify the UI and API interactions. The following abilities are needed by the UI from API requests.

Search Types:
- [x] ipv4
- [x] fqdn
- [ ] ~~url~~ Tracked in #35 
- [ ] ~~asn~~ Tracked in #31 
- [ ] ~~email~~ Tracked in #34 

Facets:
- [x] First detect datetime
- [x] Last detect datetime
- [ ] ~~Total number of feeds being searched~~ - Tracked by #122
- [x] Total number of searched feeds with hits
- [ ] ~~Total number of time the term was searched~~ - Tracked by #121
- [x] sources with hit count
- [x] feed provider / name with hit count
- [x] First import datetime
- [x] Last import datetime

Sorting:
- [ ] ~~source~~ Tracked in #117
- [x] detect datetime
- [x] import datetime
- [ ] ~~feed provider / name~~ Tracked in #118

Filtering:
- [x] detect datetime
- [x] import datetime
- [ ] ~~source~~ - Tracked in #119
- [ ] ~~feed provider~~ - Tracked in #120
- [ ] ~~feed name~~ - Tracked in #120

**Comment by justfalter** [comment]
Alright, I have to add the feed provider and name fields, then I'll be adding facets and the other stuff.

**Comment by justfalter** [comment]
**source** will become the tool that imports the data. This may be a human, in the future.
**feed_provider** will be the entity that provides us the data
**feed_name** will be the name of the feed of data supplied to us by **feed_provider**

**Comment by justfalter** [comment]
> Total number of feeds being searched

With respect to facets, they can only be put into terms of the query with which they are executing. So, if I'm querying for a specific FQDN, you'll only be able to see the feeds with which the FQDN is associated. 

This might be something that we'd want to separate out into a separate API endpoint, perhaps one specifically for querying about feeds.

**Comment by justfalter** [comment]
I'm closing this ticket out since I am now tracking all of this stuff in more specific tickets.
